# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_URL: 'https://lafresca-api.ucsc.eu.org/api/lafresca'
          envkey_VITE_UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
          envkey_COOKIE_PROTOCOL: 'https:'
          file_name: .env
      - name: Build
        run: pnpm build
      - name: Upload artifact
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: './dist'
          target: '/var/www/lafresca-frontend/html'
          rm: true
